version: "3.9"

services:
  
  postgres:
    build: 
      context: .
      dockerfile: dockerfile.postgre
    environment: 
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_USER=user
    networks: 
      network-custom:
        aliases: 
        - postgresal

  redis:
    build:
      context: .
      dockerfile: dockerfile.redis
    depends_on: 
      - postgres
    networks: 
      network-custom:
        aliases: 
        - redisal

  rabbitmq:
    build:
      context: .
      dockerfile: dockerfile.rabbitmq
    depends_on: 
      - postgres
      - redis
    networks: 
      network-custom:
        aliases: 
        - rabbitmqal

  rust:
    build:
      context: ../
      dockerfile: dockerfile.rust
    depends_on: 
      - postgres
      - redis
      - rabbitmq
    command: cargo run
    networks: 
      network-custom:
    volumes:
      - type: bind
        source: ../tmp/config.rs
        target: /tmp/rust/src/config.rs


networks:
  network-custom:
