version: "3.9"

services:
  
  postgres:
    build: 
      context: .
      dockerfile: dockerfile_postgre
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_USER=postgres

  redis:
    build:
      context: .
      dockerfile: dockerfile_redis
    ports: 
      - "6379:6379"
    depends_on: 
      - postgres

  rabbitmq:
    build:
      context: .
      dockerfile: dockerfile_rabbitmq
    ports: 
      - "5672:5672"
      - "15672:15672"
    depends_on: 
      - postgres
      - redis

  rust:
    build:
      context: ../
      dockerfile: dockerfile_rust
    network_mode: "host"
    depends_on: 
      - postgres
      - redis
      - rabbitmq
    command: cargo run